CREATE TABLE IF NOT EXISTS "MediaAssets" (
    "Id" UUID PRIMARY KEY,
    "Category" TEXT NOT NULL,
    "FileName" TEXT NOT NULL,
    "ContentType" TEXT NOT NULL,
    "SizeBytes" BIGINT NOT NULL,
    "StorageData" BYTEA NOT NULL,
    "IsImage" BOOLEAN NOT NULL DEFAULT FALSE,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "Users" (
    "Id" SERIAL PRIMARY KEY,
    "Username" TEXT NOT NULL,
    "NormalizedUsername" TEXT NOT NULL UNIQUE,
    "Email" TEXT NOT NULL,
    "NormalizedEmail" TEXT NOT NULL UNIQUE,
    "PasswordHash" TEXT NOT NULL,
    "DisplayName" TEXT NULL,
    "AboutMe" TEXT NULL,
    "AvatarUrl" TEXT NULL,
    "AvatarMediaId" UUID NULL REFERENCES "MediaAssets" ("Id") ON DELETE SET NULL,
    "BannerUrl" TEXT NULL,
    "BannerMediaId" UUID NULL REFERENCES "MediaAssets" ("Id") ON DELETE SET NULL,
    "AvatarScale" DOUBLE PRECISION NOT NULL DEFAULT 1,
    "AvatarOffsetX" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "AvatarOffsetY" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "BannerScale" DOUBLE PRECISION NOT NULL DEFAULT 1,
    "BannerOffsetX" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "BannerOffsetY" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "LastSeenAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "Role" INTEGER NOT NULL DEFAULT 0,
    "IsEmailVerified" BOOLEAN NOT NULL DEFAULT FALSE,
    "IsPrivateAccount" BOOLEAN NOT NULL DEFAULT FALSE,
    "ProfileVisibility" INTEGER NOT NULL DEFAULT 0,
    "MessagePrivacy" INTEGER NOT NULL DEFAULT 2,
    "CommentPrivacy" INTEGER NOT NULL DEFAULT 0,
    "PresenceVisibility" INTEGER NOT NULL DEFAULT 0,
    "BannedAt" TIMESTAMPTZ NULL,
    "SuspendedUntil" TIMESTAMPTZ NULL
);

CREATE TABLE IF NOT EXISTS "UserSessions" (
    "Id" UUID PRIMARY KEY,
    "UserId" INTEGER NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "RefreshTokenHash" TEXT NOT NULL,
    "PreviousRefreshTokenHash" TEXT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "LastUsedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "ExpiresAt" TIMESTAMPTZ NOT NULL,
    "RevokedAt" TIMESTAMPTZ NULL,
    "DeviceName" TEXT NULL,
    "Platform" TEXT NULL,
    "UserAgent" TEXT NULL,
    "IpAddress" TEXT NULL,
    "RevocationReason" TEXT NULL
);

CREATE TABLE IF NOT EXISTS "Posts" (
    "Id" SERIAL PRIMARY KEY,
    "UserId" INTEGER NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "Content" TEXT NOT NULL,
    "ImageUrl" TEXT NULL,
    "ImageMediaId" UUID NULL REFERENCES "MediaAssets" ("Id") ON DELETE SET NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "IsHidden" BOOLEAN NOT NULL DEFAULT FALSE,
    "IsRemoved" BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS "Likes" (
    "UserId" INTEGER NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "PostId" INTEGER NOT NULL REFERENCES "Posts" ("Id") ON DELETE CASCADE,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("UserId", "PostId")
);

CREATE TABLE IF NOT EXISTS "Comments" (
    "Id" SERIAL PRIMARY KEY,
    "Content" TEXT NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "EditedAt" TIMESTAMPTZ NULL,
    "UserId" INTEGER NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "PostId" INTEGER NOT NULL REFERENCES "Posts" ("Id") ON DELETE CASCADE,
    "ParentCommentId" INTEGER NULL REFERENCES "Comments" ("Id") ON DELETE SET NULL,
    "IsHidden" BOOLEAN NOT NULL DEFAULT FALSE,
    "IsRemoved" BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS "FriendRequests" (
    "Id" SERIAL PRIMARY KEY,
    "SenderId" INTEGER NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "ReceiverId" INTEGER NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE ("SenderId", "ReceiverId")
);

CREATE TABLE IF NOT EXISTS "Friendships" (
    "UserAId" INTEGER NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "UserBId" INTEGER NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("UserAId", "UserBId"),
    CHECK ("UserAId" < "UserBId")
);

CREATE TABLE IF NOT EXISTS "Follows" (
    "FollowerId" INTEGER NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "FollowingId" INTEGER NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("FollowerId", "FollowingId")
);

CREATE TABLE IF NOT EXISTS "FollowRequests" (
    "Id" SERIAL PRIMARY KEY,
    "RequesterId" INTEGER NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "TargetUserId" INTEGER NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "Status" INTEGER NOT NULL DEFAULT 0,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "ResolvedAt" TIMESTAMPTZ NULL
);

CREATE TABLE IF NOT EXISTS "Conversations" (
    "Id" SERIAL PRIMARY KEY,
    "UserAId" INTEGER NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "UserBId" INTEGER NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "UserAPinOrder" INTEGER NULL,
    "UserBPinOrder" INTEGER NULL,
    "UserAArchived" BOOLEAN NOT NULL DEFAULT FALSE,
    "UserBArchived" BOOLEAN NOT NULL DEFAULT FALSE,
    "UserAFavorite" BOOLEAN NOT NULL DEFAULT FALSE,
    "UserBFavorite" BOOLEAN NOT NULL DEFAULT FALSE,
    "UserAMuted" BOOLEAN NOT NULL DEFAULT FALSE,
    "UserBMuted" BOOLEAN NOT NULL DEFAULT FALSE,
    "UserADeleted" BOOLEAN NOT NULL DEFAULT FALSE,
    "UserBDeleted" BOOLEAN NOT NULL DEFAULT FALSE,
    "UserAReadAt" TIMESTAMPTZ NULL,
    "UserBReadAt" TIMESTAMPTZ NULL,
    UNIQUE ("UserAId", "UserBId"),
    CHECK ("UserAId" < "UserBId")
);

CREATE TABLE IF NOT EXISTS "Messages" (
    "Id" SERIAL PRIMARY KEY,
    "ConversationId" INTEGER NOT NULL REFERENCES "Conversations" ("Id") ON DELETE CASCADE,
    "SenderId" INTEGER NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "Content" TEXT NOT NULL DEFAULT '',
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "EditedAt" TIMESTAMPTZ NULL,
    "DeliveredToPeerAt" TIMESTAMPTZ NULL,
    "ReplyToMessageId" INTEGER NULL REFERENCES "Messages" ("Id") ON DELETE SET NULL,
    "ForwardedFromMessageId" INTEGER NULL REFERENCES "Messages" ("Id") ON DELETE SET NULL,
    "ForwardedFromUserId" INTEGER NULL REFERENCES "Users" ("Id") ON DELETE SET NULL,
    "DeletedForUserA" BOOLEAN NOT NULL DEFAULT FALSE,
    "DeletedForUserB" BOOLEAN NOT NULL DEFAULT FALSE,
    "IsHidden" BOOLEAN NOT NULL DEFAULT FALSE,
    "IsRemoved" BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS "MessageAttachments" (
    "Id" SERIAL PRIMARY KEY,
    "MessageId" INTEGER NOT NULL REFERENCES "Messages" ("Id") ON DELETE CASCADE,
    "MediaAssetId" UUID NULL REFERENCES "MediaAssets" ("Id") ON DELETE SET NULL,
    "FileName" TEXT NOT NULL,
    "FileUrl" TEXT NOT NULL,
    "ContentType" TEXT NOT NULL,
    "SizeBytes" BIGINT NOT NULL DEFAULT 0,
    "IsImage" BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS "Notifications" (
    "Id" SERIAL PRIMARY KEY,
    "UserId" INTEGER NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "ActorUserId" INTEGER NULL REFERENCES "Users" ("Id") ON DELETE SET NULL,
    "Type" TEXT NOT NULL,
    "Text" TEXT NOT NULL,
    "IsRead" BOOLEAN NOT NULL DEFAULT FALSE,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "PostId" INTEGER NULL REFERENCES "Posts" ("Id") ON DELETE SET NULL,
    "CommentId" INTEGER NULL REFERENCES "Comments" ("Id") ON DELETE SET NULL,
    "ConversationId" INTEGER NULL REFERENCES "Conversations" ("Id") ON DELETE SET NULL,
    "MessageId" INTEGER NULL REFERENCES "Messages" ("Id") ON DELETE SET NULL,
    "RelatedUserId" INTEGER NULL REFERENCES "Users" ("Id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "UserBlocks" (
    "BlockerId" INTEGER NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "BlockedUserId" INTEGER NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("BlockerId", "BlockedUserId")
);

CREATE TABLE IF NOT EXISTS "DevicePushTokens" (
    "UserId" INTEGER NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "DeviceId" TEXT NOT NULL,
    "Token" TEXT NOT NULL,
    "DeviceName" TEXT NULL,
    "Platform" TEXT NOT NULL,
    "AppVersion" TEXT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "LastSeenAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "RevokedAt" TIMESTAMPTZ NULL,
    PRIMARY KEY ("UserId", "DeviceId")
);

CREATE TABLE IF NOT EXISTS "AuthTokens" (
    "Id" UUID PRIMARY KEY,
    "UserId" INTEGER NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "Kind" TEXT NOT NULL,
    "TokenHash" TEXT NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "ExpiresAt" TIMESTAMPTZ NOT NULL,
    "ConsumedAt" TIMESTAMPTZ NULL
);

CREATE TABLE IF NOT EXISTS "Reports" (
    "Id" SERIAL PRIMARY KEY,
    "Source" TEXT NOT NULL DEFAULT 'user',
    "TargetType" TEXT NOT NULL,
    "TargetId" INTEGER NOT NULL,
    "TargetUserId" INTEGER NULL REFERENCES "Users" ("Id") ON DELETE SET NULL,
    "Reason" TEXT NOT NULL,
    "CustomNote" TEXT NULL,
    "Status" TEXT NOT NULL DEFAULT 'Open',
    "ReporterUserId" INTEGER NULL REFERENCES "Users" ("Id") ON DELETE SET NULL,
    "AssignedModeratorUserId" INTEGER NULL REFERENCES "Users" ("Id") ON DELETE SET NULL,
    "Resolution" TEXT NOT NULL DEFAULT 'None',
    "ResolutionNote" TEXT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "UpdatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "ResolvedAt" TIMESTAMPTZ NULL
);

CREATE TABLE IF NOT EXISTS "ModerationActions" (
    "Id" SERIAL PRIMARY KEY,
    "ActorUserId" INTEGER NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE,
    "TargetUserId" INTEGER NULL REFERENCES "Users" ("Id") ON DELETE SET NULL,
    "ActionType" TEXT NOT NULL,
    "TargetType" TEXT NULL,
    "TargetId" INTEGER NULL,
    "ReportId" INTEGER NULL REFERENCES "Reports" ("Id") ON DELETE SET NULL,
    "Note" TEXT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "ExpiresAt" TIMESTAMPTZ NULL
);

ALTER TABLE IF EXISTS "Users" ADD COLUMN IF NOT EXISTS "AvatarMediaId" UUID NULL REFERENCES "MediaAssets" ("Id") ON DELETE SET NULL;
ALTER TABLE IF EXISTS "Users" ADD COLUMN IF NOT EXISTS "BannerMediaId" UUID NULL REFERENCES "MediaAssets" ("Id") ON DELETE SET NULL;
ALTER TABLE IF EXISTS "Posts" ADD COLUMN IF NOT EXISTS "ImageMediaId" UUID NULL REFERENCES "MediaAssets" ("Id") ON DELETE SET NULL;
ALTER TABLE IF EXISTS "MessageAttachments" ADD COLUMN IF NOT EXISTS "MediaAssetId" UUID NULL REFERENCES "MediaAssets" ("Id") ON DELETE SET NULL;
