package app

import (
	"net/http"

	"github.com/go-chi/chi/v5"
)

func (s *Server) registerMobileRoutes(router chi.Router) {
	router.Route("/api", func(r chi.Router) {
		r.Route("/auth", func(r chi.Router) {
			r.Post("/register", s.handleRegister)
			r.Post("/login", s.handleLogin)
			r.Post("/refresh", s.handleRefresh)
			r.Post("/refresh-token", s.handleRefresh)
			r.Get("/check-username", s.mobileHandleCheckRegistrationUsername)
			r.Get("/check-email", s.mobileHandleCheckRegistrationEmail)
			r.Post("/verify-email", s.handleVerifyEmail)
			r.Post("/resend-verification", s.handleResendVerification)
			r.Post("/forgot-password", s.handleForgotPassword)
			r.Post("/reset-password", s.handleResetPassword)

			r.Group(func(r chi.Router) {
				r.Use(s.requireAuth)
				r.Post("/logout", s.handleLogout)
				r.Post("/logout-all", s.mobileHandleLogoutAllSessions)
				r.Get("/sessions", s.mobileHandleGetSessions)
				r.Delete("/sessions/{sessionID}", s.mobileHandleRevokeSession)
				r.Get("/profile", s.mobileHandleProfile)
				r.Get("/profile/{userID}", s.mobileHandleUserProfile)
				r.Put("/profile", s.mobileHandleUpdateProfile)
				r.Put("/profile/media", s.mobileHandleUpdateProfileMedia)
			})
		})

		r.Group(func(r chi.Router) {
			r.Use(s.requireAuth)
			r.Get("/sync/stream", s.handleSyncStream)
			r.Get("/users/check-username", s.mobileHandleCheckUsername)
			r.Get("/users", s.mobileHandleUsers)
			r.Get("/users/search", s.mobileHandleSearchUsers)
			r.Get("/users/me/privacy", s.mobileHandleGetPrivacy)
			r.Put("/users/me/privacy", s.mobileHandleUpdatePrivacy)
			r.Get("/feed", s.mobileHandleFeed)
			r.Get("/feed/following", s.mobileHandleFollowingFeed)
			r.Post("/posts", s.mobileHandleCreatePost)
			r.Get("/posts/{postID}", s.mobileHandleGetPost)
			r.Delete("/posts/{postID}", s.handleDeletePost)
			r.Get("/posts/user/{userID}", s.mobileHandleUserPosts)
			r.Post("/posts/{postID}/like", s.mobileHandleToggleLike)
			r.Get("/posts/{postID}/comments", s.mobileHandleComments)
			r.Post("/posts/{postID}/comments", s.mobileHandleCreateComment)
			r.Put("/posts/{postID}/comments/{commentID}", s.mobileHandleUpdateComment)
			r.Delete("/posts/{postID}/comments/{commentID}", s.mobileHandleDeleteComment)
			r.Post("/follows/{userID}", s.mobileHandleToggleFollow)
			r.Get("/follows/{userID}/following", s.mobileHandleFollowingList)
			r.Get("/follows/{userID}/followers", s.mobileHandleFollowersList)
			r.Get("/follows/followings", s.mobileHandleMyFollowingList)
			r.Get("/follows/followers", s.mobileHandleMyFollowersList)
			r.Get("/follows/check/{userID}", s.mobileHandleIsFollowing)
			r.Get("/follows/{userID}/followers/count", s.mobileHandleFollowersCount)
			r.Get("/follows/requests", s.mobileHandleIncomingFollowRequests)
			r.Post("/follows/requests/{requestID}/approve", s.mobileHandleApproveFollowRequest)
			r.Post("/follows/requests/{requestID}/reject", s.mobileHandleRejectFollowRequest)
			r.Get("/friends", s.mobileHandleFriends)
			r.Get("/friends/requests/incoming", s.mobileHandleIncomingFriendRequests)
			r.Get("/friends/requests/outgoing", s.mobileHandleOutgoingFriendRequests)
			r.Post("/friends/requests/{userID}", s.mobileHandleSendFriendRequestCompat)
			r.Post("/friends/requests/{requestID}/accept", s.handleAcceptFriendRequest)
			r.Delete("/friends/requests/{requestID}", s.handleDeleteFriendRequest)
			r.Delete("/friends/{userID}", s.handleRemoveFriend)
			r.Get("/conversations", s.mobileHandleConversations)
			r.Post("/conversations/direct/{userID}", s.mobileHandleDirectConversation)
			r.Get("/conversations/{conversationID}/messages", s.mobileHandleMessages)
			r.Post("/conversations/{conversationID}/messages", s.mobileHandleSendMessage)
			r.Post("/conversations/{conversationID}/messages/forward", s.mobileHandleForwardMessage)
			r.Put("/conversations/{conversationID}/messages/{messageID}", s.mobileHandleUpdateMessage)
			r.Delete("/conversations/{conversationID}/messages/{messageID}", s.mobileHandleDeleteMessage)
			r.Post("/message/delete-for-all", s.mobileHandleDeleteMessageForAll)
			r.Post("/chat/pin", s.mobileHandlePinConversation)
			r.Post("/chat/archive", s.mobileHandleArchiveConversation)
			r.Post("/chat/favorite", s.mobileHandleFavoriteConversation)
			r.Post("/chat/mute", s.mobileHandleMuteConversation)
			r.Delete("/chat", s.mobileHandleDeleteConversation)
			r.Post("/chat/clear-history", s.mobileHandleClearConversationHistory)
			r.Post("/chat/block-user", s.mobileHandleBlockUser)
			r.Post("/chat/unblock-user", s.mobileHandleUnblockUser)
			r.Get("/chat/blocked-users", s.mobileHandleBlockedUsers)
			r.Post("/chat/typing-start", s.mobileHandleTypingStart)
			r.Post("/chat/typing-stop", s.mobileHandleTypingStop)
			r.Get("/notifications", s.mobileHandleNotifications)
			r.Get("/notifications/summary", s.handleNotificationSummary)
			r.Post("/notifications/{notificationID}/read", s.handleReadNotification)
			r.Post("/notifications/read-all", s.handleReadAllNotifications)
			r.Post("/notifications/push-token", s.mobileHandleRegisterPushToken)
			r.Delete("/notifications/push-token", s.mobileHandleRemovePushToken)
			r.Post("/reports", s.handleCreateReport)
			r.Get("/moderation/reports", s.handleModerationReports)
			r.Get("/moderation/reports/{reportID}", s.handleModerationReportDetail)
			r.Post("/moderation/reports/{reportID}/assign", s.handleAssignReport)
			r.Post("/moderation/reports/{reportID}/resolve", s.handleResolveReport)
			r.Post("/moderation/actions/warn", s.handleWarnUser)
			r.Post("/moderation/actions/suspend", s.handleSuspendUser)
			r.Post("/moderation/actions/ban", s.handleBanUser)
			r.Post("/moderation/actions/unban", s.handleUnbanUser)
			r.Post("/admin/roles/moderators/{userID}", s.handleAssignModerator)
			r.Delete("/admin/roles/moderators/{userID}", s.handleRemoveModerator)
		})
	})
}

func (s *Server) mobileHandleNoop(w http.ResponseWriter, _ *http.Request) {
	writeJSON(w, http.StatusOK, map[string]bool{"ok": true})
}
